export const ONBOARDING_PAGES = [
    {title: 'ONBOARDING.PAGE_1_TITLE', body: 'ONBOARDING.PAGE_1_TEXT'},
    {title: 'ONBOARDING.PAGE_2_TITLE', body: 'ONBOARDING.PAGE_2_TEXT'},
    {title: 'ONBOARDING.PAGE_3_TITLE', body: 'ONBOARDING.PAGE_3_TEXT'},
    {title: 'ONBOARDING.PAGE_4_TITLE', body: 'ONBOARDING.PAGE_4_TEXT'},
];